# .github/workflows/security-scan.yml
name: Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask gunicorn bandit safety

      - name: Run Bandit (Static Code Analysis)
        run: bandit -r backend/

      - name: Run Safety (Dependency Vulnerability Scan)
        run: safety check --full-report

      - name: Trivy FS Scan (IaC & configs)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "http://localhost:8000"
